from dataclasses import dataclass
from typing import List


@dataclass
class RuleTrigger:
    """
    Represents a successfully triggered scoring rule.

    Unlike a generic rule evaluation object,
    this structure specifically captures ONLY
    rules that actually matched/activated.

    Purpose:
    - Track scoring contributions
    - Provide explainability
    - Support auditing/debugging
    - Feed AI explanation layers
    - Power frontend score breakdowns

    Example:
    A rule may trigger because:
    - Lead has business email
    - Lead recently engaged
    - Pipeline probability is high

    This object stores the resulting trigger metadata.
    """

    # ------------------------------------------------------
    # Unique rule identifier
    #
    # Example:
    # "RULE_HIGH_PIPELINE_INTENT"
    # "RULE_BUSINESS_EMAIL"
    # ------------------------------------------------------
    rule_id: str

    # ------------------------------------------------------
    # Human-readable rule name
    #
    # Example:
    # "Business Email Detected"
    # "Recent Activity Found"
    # ------------------------------------------------------
    name: str

    # ------------------------------------------------------
    # High-level scoring category
    #
    # Common categories:
    # - fit
    # - behavior
    # - quality
    # - penalty
    #
    # Used for:
    # - Score aggregation
    # - Reporting
    # - Explainability
    # ------------------------------------------------------
    category: str

    # ------------------------------------------------------
    # Score contribution generated by this rule
    #
    # Positive values:
    # Increase lead score
    #
    # Negative values:
    # Apply penalties/risk deductions
    #
    # Example:
    # +20
    # -15
    # ------------------------------------------------------
    score: float

    # ------------------------------------------------------
    # List of signals/fields that caused
    # the rule to trigger
    #
    # Example:
    # [
    #   "sf_email",
    #   "sf_created_at"
    # ]
    #
    # Useful for:
    # - Explainability
    # - Traceability
    # - Rule debugging
    # ------------------------------------------------------
    matched_signals: List[str]

    # ------------------------------------------------------
    # Human-readable explanation describing
    # why the rule triggered.
    #
    # Example:
    # "Corporate email domain detected"
    # "Lead activity within last 24 hours"
    #
    # Used in:
    # - Sales dashboards
    # - AI-generated summaries
    # - Audit logs
    # ------------------------------------------------------
    reason: str